---
title: "Probability Theory"
---

::: callout-note
You can delete everything in here and start fresh.
:::

This is a `.qmd` file. It is plain text with special features. Any time you write just like this, it will be compiled to normal text in the website. If you put a \# in front of your text, it will create a top level-header.

To learn more about Quarto websites visit <https://quarto.org/docs/websites>.

# Assignment I

```{r}
# Given probabilities
P_T <- 0.8  # Probability of being on time
P_Tprime <- 0.2  # Probability of not being on time
P_S <- 0.3  # Probability of a change in scope
P_Sprime <- 0.7  # Probability of no change in scope

# Calculating probabilities
P_T_and_S <- P_T * P_S
P_T_and_Sprime <- P_T * P_Sprime
P_Tprime_and_S <- P_Tprime * P_S
P_Tprime_and_Sprime <- P_Tprime * P_Sprime

# Sum of probabilities
sum_of_probabilities <- P_T_and_S + P_T_and_Sprime + P_Tprime_and_S + P_Tprime_and_Sprime

# Displaying the results
cat("P(T ∩ S):", P_T_and_S, "\n")
cat("P(T ∩ S'): ", P_T_and_Sprime, "\n")
cat("P(T' ∩ S):", P_Tprime_and_S, "\n")
cat("P(T' ∩ S'): ", P_Tprime_and_Sprime, "\n")
cat("Sum of probabilities:", sum_of_probabilities, "\n")
```
# Assignment II
```{r}
# Given probabilities
P_A <- 0.423
P_B <- 0.278
P_C <- 0.1
P_A_intersect_B <- 0.073
P_B_intersect_C <- 0.033
P_A_intersect_C <- 0.088
P_A_intersect_B_intersect_C <- 0.005

# Percentage of customers using all three devices
P_all_three <- P_A_intersect_B_intersect_C * 100
P_all_three

# Calculate the percentage of customers using at least two devices
P_at_least_two <- (P_A + P_B + P_C - P_A_intersect_B - P_B_intersect_C - P_A_intersect_C + P_A_intersect_B_intersect_C) * 100
P_at_least_two

# Calculate the percentage of customers using only one device
P_only_one <- (P_A - P_A_intersect_B - P_A_intersect_C + P_A_intersect_B_intersect_C +
               P_B - P_A_intersect_B - P_B_intersect_C + P_A_intersect_B_intersect_C +
               P_C - P_A_intersect_C - P_B_intersect_C + P_A_intersect_B_intersect_C) * 100
P_only_one

```
# Assignment III
```{r}
# Given probabilities
P_B_A <- 0.97
P_B_notA <- 0.01
P_A <- 0.04
not_P_A <- 1 - P_A

# Calculate the probability B
P_B <- P_B_A * P_A + P_B_notA* not_P_A
P_B

# Calculate the probability A|B
P_A_B <- P_B_A * P_A /P_B
P_A_B

# Calculate the probability not_A|B
P_not_A_B <- P_B_notA * not_P_A / P_B
P_not_A_B

# The following sentence
# These results show that in case the alarm is triggered, there is a possibility of about 19.83% that the product is flawless and a probability of 80.16% that the product is faulty.

```

