---
title: "Statistical Concepts"
---

# Assignmnet

```{r}
# Load the file
random_vars <- readRDS("Causal_Data_Science_Data/random_vars.rds")
str(random_vars)
# Create a Data Frame
df1=data.frame(random_vars)
# 1.Find the values of mean, variance and standard deviation
```
```{r}
# 1.Mean 
mean(df1$age)
mean(df1$income)
```
```{r}
# 2. Variance
var(df1$age)
var(df1$income)
```
```{r}
# 3. Standard deviation
sd(df1$age)
sd(df1$income)
```
```{r}
# 2. The calculated Standard deviations are on vastly different scales. In this case, the large difference in values suggests that the Data Sets corresponding to these standard deviations have very different degrees of variability. Due to this reason it does not make sense to compare them.
```
```{r}
# 3 Calculate Covariance and Correlation
cov(df1)
```
```{r}
cor(df1)
```
```{r}
# 4. Correlation is generally easier to interpret and compare than covariance especially when dealing with variables on different scales.It provides a standardized measure of the strength and direction of the linear relationship between two variables.
```
```{r}
# 5. Conditional Expected value
age_18 <- subset(df1, age<=18, select = c(age,income))
mean(age_18$income)
```
```{r}
age_65 <- subset(df1, age>=65, select = c(age,income))
mean(age_65$income)
```
```{r}
age_18_65 <- subset(df1, age>=18 & age<65, select = c(age,income))
mean(age_18_65$income)
```











