---
title: "Regression and Statistical Inference"
---

# Assignmnet

```{r}
library(tidyverse)
```
```{r}
# Load the file
car_prices <- readRDS("Causal_Data_Science_Data/car_prices.rds")
# Create a Data Frame
df=data.frame(car_prices)
```
```{r}
# 1 Check the dimensions
dim(df)
```
```{r}
# 181 rows and 22 columns
```
```{r}
head(df)
df
```
```{r}
glimpse(df)
```
```{r}
summary(df)
```
```{r}
# 2. The data types present are character and double data type.
```
```{r}
# 3. Linear regression
lm_all <- lm(price ~ ., data = df)
summary(lm_all)
```
```{r}
# 4 Choosing a regressor
lm_imp <- lm(price ~ enginesize , data = df)
summary(lm_imp)
```
```{r}
# 4.1 The regressor used was enginesize and it belongs to the numeric variables (discrete/continous). It can take numeric values
# 4.2 As our estimate is positive (170.064), we have a positive effect. As a result increasing the enginesize would increase the price of the car.
# 4.3 Yes, it  is satistically significant as the p value is lower than our significance level (0.05)
```
```{r}
# 5 Adding a new variable
df %>% mutate(seatheating = TRUE)
```
```{r}
# Changing the variables from logical variables to numerical variables
df1<- df %>% mutate(seatheating = 1)
df1
```
```{r}
# New regression
lm_new <- lm(price ~ seatheating , data = df1)
summary(lm_new)
```
```{r}
# There is no coefficient for this regression as there is no relation between seat heating and pricing.
```













