---
title: "Directed Acyclic Graphs"
---

# Assignment

```{r}
# Load packages
library(tidyverse)
library(dagitty)
library(ggdag)
```
```{r}
# DAG for ParkingSpots
Parkingspots <- dagify(
  ParkingSpots ~ Location,
  Sales ~ Location,
  Sales ~ ParkingSpots,
  coords = list(x = c(Sales = 3, Location = 2, ParkingSpots = 1),
                y = c(Sales = 0, Location = 1, ParkingSpots = 0))
)
# Plot DAG
ggdag(Parkingspots, use_labels = "name", text =  F) + theme_dag()
```
```{r}
# Load the file
car_prices <- readRDS("Causal_Data_Science_Data/customer_sat.rds")
# Create a Data Frame
df=data.frame(car_prices)
df
```
```{r}
# 2.1 Include only significant regressors
#lm_2_1 is the regresssion of satisfaction on follow_ups
lm_2_1 <- lm(satisfaction ~ follow_ups , data = df)
summary(lm_2_1)
```
```{r}
# 2.2 Regress satisfaction on follow_ups and account for subscription
#lm_2_2 is the regresssion of satisfaction on follow_ups and account for subscription
lm_2_2 <- lm(satisfaction ~ follow_ups + subscription , data = df)
summary(lm_2_2)
```

```{r}
# 3 Comparing the coefficients 

# In the first regression with satisfaction on follow_ups are negatively correlated as increase in satisfaction with the product and service will decrease the follow_up calls to the clients.

# In the second regression with satisfaction on follow_ups and account for subscription is highly correlated premium subscription levels than elite subscription levels.
```
```{r}
# 4 Plot the data
# Not conditioning on subscription
subscription_not_cond <- ggplot(df, aes(x = satisfaction, y = follow_ups)) +
  geom_point(alpha = .8) +
  stat_smooth(method = "lm", se = F)

# Conditioning on subscription 
subscription_cond <- ggplot(df, aes(x = satisfaction, y = follow_ups, color = subscription)) +
  geom_point(alpha = .8) +
  stat_smooth(method = "lm", se = F) +
  theme(legend.position = "right")

# Plot both plots
subscription_not_cond
subscription_cond
```









