---
title: "Instrumental Variables"
author: "Shashidhar Cheeti"
---

```{r}
library(tidyverse)
library(dplyr)
library(ggdag)
library(dagitty)
```
```{r}
# Load the file
rand_enc <- readRDS("Causal_Data_Science_Data/rand_enc.rds")
# Create a Data Frame
df=data.frame(rand_enc)
head(df)
glimpse(df)
summary(df)
```
1. Plot DAG
```{r}
App_usuage <- dagify(
  timespent ~ used_ftr,
  used_ftr ~ rand_enc,
  coords = list(x = c(timespent = 3,  used_ftr = 1, rand_enc = -1),
                y = c(timespent = 0,  used_ftr = 0, rand_enc = 0))
)
# Plot DAG
ggdag(App_usuage, use_labels = "name", text =  F) + theme_dag()
```
From my understanding of these relationships from DAG, time spent would be the outcome which depends on the used new feature (used_ftr) would be the treatment variable and randomized encouragement trial (rand_enc) would be instrumental variable.

2. Compute the naive, biased estimate.
```{r}
model_biased <- lm(time_spent ~ used_ftr, data = df)
summary(model_biased)
```
```{r}
model_naive <- lm(rand_enc ~ used_ftr, data = df)
summary(model_naive)
```







